### ISSUE TITLE
Path access under jruby

### ISSUE THREAD

**Issue by svoboda-jan** [vjoel/fsdb#3]
Hi, I've been using FSDB on MRI and recently tested it in jruby, with the following code:

``` ruby
db = FSDB::Database.new '/tmp/test'

db["/"].each do |file|
  p file
end
```

It works on MRI (`2.0.0-p247`), but throws the following exception in jruby (`1.7.4`):

```
Errno::EACCES: Permission denied - /tmp/test/
             initialize at org/jruby/RubyFile.java:334
                   open at org/jruby/RubyIO.java:1144
         open_read_lock at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:384
                  fetch at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:739
       object_exclusive at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:374
  sync_object_exclusive at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:105
            synchronize at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/modex.rb:113
  sync_object_exclusive at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:105
       object_exclusive at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:373
        use_cache_entry at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:352
       object_exclusive at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:372
                  fetch at /Users/jansvoboda/.rbenv/versions/jruby-1.7.4/lib/ruby/gems/shared/gems/fsdb-0.7.3/lib/fsdb/database.rb:738
                 (root) at /Users/jansvoboda/Documents/dialplan/app/event_handlers/dtmf_event_handler.rb:11
```

Changing permissions to `777` on the directory does not have any effect.

**Comment by vjoel** [comment]
On 08/28/2013 01:45 PM, Jan Svoboda wrote:

> Hi, I've been using FSDB on MRI and recently tested it in jruby, with
> the following code:
> 
> db  =  FSDB::Database.new  '/tmp/test'
> 
> db["/"].each  do  |file|
>    p  file
> end
> 
> It works on MRI (|2.0.0-p247|), but throws the following exception in
> jruby (|1.7.4|):
> 
> |Errno::EACCES: Permission denied - /tmp/test/

Alas, it is a limitation of the java file API:

http://jira.codehaus.org/browse/JRUBY-4033

For example:

$ jruby -e 'p File.open("/etc", "r")'
Errno::EACCES: Permission denied - /etc
   initialize at org/jruby/RubyFile.java:334
         open at org/jruby/RubyIO.java:1144
       (root) at -e:1

But with MRI 2.0:

$ ruby -e 'p File.open("/etc", "r")'
#File:/etc
$

I suppose FSDB could work around this using

   Dir.new('/tmp').entries

...

Thanks for your interest in FSDB!

Joel

**Comment by svoboda-jan** [comment]
Thanks for the quick reply! Didn't realise it could be this limitation since it complains about permissions.
